SET ECHO OFF
SET LINESIZE 3277
SET LONG 90000
SET LONGCHUNKSIZE 90000
SET WRAP OFF
SET HEADING ON
SET COLSEP ';'
SET FEEDBACK ON
SET TRIMSPOOL ON
SET TRIMOUT ON
SET PAGESIZE 0
SET NEWPAGE None
SET VERIFY OFF
SET UNDERLINE '-'
SET TERMOUT ON

COLUMN timestamp HEADING 'TimeStamp'
COLUMN datavalue HEADING 'DataValue'

SELECT to_char(timestamp, 'YYYYMMDD HH24:MI:SS'), datavalue FROM NumericLog WHERE LogName ='&1' AND TimeStamp >= sysdate-&2;

exit